openapi: 3.0.1
info:
  title: Kwitter
  version: "1.0.0"
servers:
  - url: http://localhost:4000
    description: localhost
  - url: https://protected-eyrie-19608.herokuapp.com
    description: Production Server
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
paths:
  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  id:
                    type: integer
                  token:
                    type: string
  /auth/logout:
    get:
      summary: Logout a user
      tags:
        - Auth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /auth/register:
    post:
      summary: "Register a new user"
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                displayName:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  displayName:
                    type: string
  /layouts/:
    post:
      summary: "Saves a layout"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                layout:
                  type: object
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
